apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: muthuvenkatachalam-tls
spec:
  secretName: muthuvenkatachalam-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: muthuvenkatachalam.tk
  dnsNames:
    - muthuvenkatachalam.tk
    - www.muthuvenkatachalam.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - muthuvenkatachalam.tk
          - www.muthuvenkatachalam.tk
